package edu.ucam.aplicacion;


public class CargaDeDatos {
 //**Clase para cargar datos*/
	
	
	public static void CargarDatos (){
		
		
		Arco Arco1 = new Arco("Arco1", 338, 963, 10 );
		Arco Arco2 = new Arco("Arco2", 840, 817, 10 );
		Arco Arco3 = new Arco("Arco3", 744, 933, 2 );
		Arco Arco4 = new Arco("Arco4", 739, 1674, 9 );
		Arco Arco5 = new Arco("Arco5", 508, 1425, 1 );
		Arco Arco6 = new Arco("Arco6", 854, 805, 3 );
		Arco Arco7 = new Arco("Arco7", 128, 714, 3 );
		Arco Arco8 = new Arco("Arco8", 268, 1926, 9 );
		Arco Arco9 = new Arco("Arco9", 728, 766, 6 );
		Arco Arco10 = new Arco("Arco10", 590, 1442, 4 );
		Arco Arco11 = new Arco("Arco11", 194, 599, 0 );
		Arco Arco12 = new Arco("Arco12", 520, 1936, 0 );
		Arco Arco13 = new Arco("Arco13", 504, 1771, 10 );
		Arco Arco14 = new Arco("Arco14", 935, 1508, 9 );
		Arco Arco15 = new Arco("Arco15", 648, 1703, 4 );
		Arco Arco16 = new Arco("Arco16", 797, 1967, 4 );
		Arco Arco17 = new Arco("Arco17", 362, 1321, 0 );
		Arco Arco18 = new Arco("Arco18", 367, 1637, 10 );
		Arco Arco19 = new Arco("Arco19", 958, 871, 1 );
		Arco Arco20 = new Arco("Arco20", 290, 1888, 10 );
		Arco Arco21 = new Arco("Arco21", 356, 1552, 6 );
		Arco Arco22 = new Arco("Arco22", 562, 1393, 3 );
		Arco Arco23 = new Arco("Arco23", 767, 1687, 6 );
		Arco Arco24 = new Arco("Arco24", 770, 833, 2 );
		Arco Arco25 = new Arco("Arco25", 891, 1812, 6 );
		Arco Arco26 = new Arco("Arco26", 463, 987, 10 );
		Arco Arco27 = new Arco("Arco27", 739, 795, 1 );
		Arco Arco28 = new Arco("Arco28", 423, 602, 7 );
		Arco Arco29 = new Arco("Arco29", 131, 643, 6 );
		Arco Arco30 = new Arco("Arco30", 548, 794, 10 );
		Arco Arco31 = new Arco("Arco31", 0, 0, 0 );
		Arco Arco32 = new Arco("Arco31", 1000, 1000, 10 );
		Hacha Hacha1 = new Hacha("Hacha1", 3670, 1640 );
		Hacha Hacha2 = new Hacha("Hacha2", 7781, 1441 );
		Hacha Hacha3 = new Hacha("Hacha3", 8332, 1791 );
		Hacha Hacha4 = new Hacha("Hacha4", 6421, 849 );
		Hacha Hacha5 = new Hacha("Hacha5", 5140, 1686 );
		Hacha Hacha6 = new Hacha("Hacha6", 3141, 998 );
		Hacha Hacha7 = new Hacha("Hacha7", 9964, 594 );
		Hacha Hacha8 = new Hacha("Hacha8", 4192, 1987 );
		Hacha Hacha9 = new Hacha("Hacha9", 4939, 738 );
		Hacha Hacha10 = new Hacha("Hacha10", 4304, 1421 );
		Hacha Hacha11 = new Hacha("Hacha11", 4005, 812 );
		Hacha Hacha12 = new Hacha("Hacha12", 3823, 836 );
		Hacha Hacha13 = new Hacha("Hacha13", 6287, 1935 );
		Hacha Hacha14 = new Hacha("Hacha14", 3979, 1552 );
		Hacha Hacha15 = new Hacha("Hacha15", 7663, 607 );
		Hacha Hacha16 = new Hacha("Hacha16", 4730, 1151 );
		Hacha Hacha17 = new Hacha("Hacha17", 9435, 1802 );
		Hacha Hacha18 = new Hacha("Hacha18", 8675, 934 );
		Hacha Hacha19 = new Hacha("Hacha19", 9335, 983 );
		Hacha Hacha20 = new Hacha("Hacha20", 7033, 880 );
		Hacha Hacha21 = new Hacha("Hacha21", 4583, 1239 );
		Hacha Hacha22 = new Hacha("Hacha22", 7652, 944 );
		Hacha Hacha23 = new Hacha("Hacha23", 6521, 1956 );
		Hacha Hacha24 = new Hacha("Hacha24", 8913, 1877 );
		Hacha Hacha25 = new Hacha("Hacha25", 8579, 1367 );
		Hacha Hacha26 = new Hacha("Hacha26", 9241, 1071 );
		Hacha Hacha27 = new Hacha("Hacha27", 9170, 581 );
		Hacha Hacha28 = new Hacha("Hacha28", 3094, 1571 );
		Hacha Hacha29 = new Hacha("Hacha29", 4506, 963 );
		Hacha Hacha30 = new Hacha("Hacha30", 6163, 500 );
		Espada Espada1 = new Espada("Espada1", 9874, 862 );
		Espada Espada2 = new Espada("Espada2", 4408, 1389 );
		Espada Espada3 = new Espada("Espada3", 4463, 587 );
		Espada Espada4 = new Espada("Espada4", 7982, 1582 );
		Espada Espada5 = new Espada("Espada5", 5676, 1700 );
		Espada Espada6 = new Espada("Espada6", 5660, 1790 );
		Espada Espada7 = new Espada("Espada7", 3358, 1366 );
		Espada Espada8 = new Espada("Espada8", 7271, 1925 );
		Espada Espada9 = new Espada("Espada9", 8596, 1857 );
		Espada Espada10 = new Espada("Espada10", 5036, 972 );
		Espada Espada11 = new Espada("Espada11", 8285, 852 );
		Espada Espada12 = new Espada("Espada12", 6154, 1681 );
		Espada Espada13 = new Espada("Espada13", 8370, 1294 );
		Espada Espada14 = new Espada("Espada14", 4961, 794 );
		Espada Espada15 = new Espada("Espada15", 6971, 1413 );
		Espada Espada16 = new Espada("Espada16", 5578, 1459 );
		Espada Espada17 = new Espada("Espada17", 4558, 714 );
		Espada Espada18 = new Espada("Espada18", 3702, 1769 );
		Espada Espada19 = new Espada("Espada19", 4059, 957 );
		Espada Espada20 = new Espada("Espada20", 8653, 1301 );
		Espada Espada21 = new Espada("Espada21", 4122, 1003 );
		Espada Espada22 = new Espada("Espada22", 8351, 1018 );
		Espada Espada23 = new Espada("Espada23", 8692, 1365 );
		Espada Espada24 = new Espada("Espada24", 9375, 1013 );
		Espada Espada25 = new Espada("Espada25", 7366, 1508 );
		Espada Espada26 = new Espada("Espada26", 5529, 1292 );
		Espada Espada27 = new Espada("Espada27", 9200, 1942 );
		Espada Espada28 = new Espada("Espada28", 8058, 1945 );
		Espada Espada29 = new Espada("Espada29", 6867, 1305 );
		Espada Espada30 = new Espada("Espada30", 8032, 1411 );
		
		

		Reino Reino1 = new Reino("Invernalia", "Casa Stark");
		Reino Reino2 = new Reino("Aguasdulces", "Casa Tully");
		Reino Reino3 = new Reino("El Nido de �guilas", "Casa Arryn");
		Reino Reino4 = new Reino("Roca Casterly", "Casa Lannister");
		Reino Reino5 = new Reino("Basti�n de las Tormentas", "Casa Baratheon");
		Reino Reino6 = new Reino("Altojard�n", "Casa Tyrell");
		Reino Reino7 = new Reino("Lanza del Sol", "Casa Martell");

		GuerreroHumano Reino1Soldado1 = new GuerreroHumano("InvernaliaSoldado1", 58, Espada25, Reino1, 53);
		GuerreroHumano Reino1Soldado2 = new GuerreroHumano("InvernaliaSoldado2", 72, Espada16, Reino1, 100);
		GuerreroHumano Reino1Soldado3 = new GuerreroHumano("InvernaliaSoldado3", 51, Hacha22, Reino1, 59);
		GuerreroHumano Reino1Soldado4 = new GuerreroHumano("InvernaliaSoldado4", 72, Arco4, Reino1, 99);
		GuerreroHumano Reino1Soldado5 = new GuerreroHumano("InvernaliaSoldado5", 39, Hacha26, Reino1, 46);
		GuerreroHumano Reino1Soldado6 = new GuerreroHumano("InvernaliaSoldado6", 74, Espada2, Reino1, 97);
		GuerreroHumano Reino1Soldado7 = new GuerreroHumano("InvernaliaSoldado7", 43, Espada19, Reino1, 10);
		GuerreroHumano Reino1Soldado8 = new GuerreroHumano("InvernaliaSoldado8", 46, Espada23, Reino1, 32);
		GuerreroHumano Reino1Soldado9 = new GuerreroHumano("InvernaliaSoldado9", 52, Arco17, Reino1, 96);
		GuerreroHumano Reino1Soldado10 = new GuerreroHumano("InvernaliaSoldado10", 84, Arco19, Reino1, 26);
		GuerreroHumano Reino1Soldado11 = new GuerreroHumano("InvernaliaSoldado11", 1, Arco31, Reino1, 0);
		GuerreroHumano Reino1Soldado12 = new GuerreroHumano("InvernaliaSoldado12", 99, Arco32, Reino1, 100);
		GuerreroHumano Reino2Soldado11 = new GuerreroHumano("AguasdulcesSoldado1", 31, Hacha10, Reino2, 66);
		GuerreroHumano Reino2Soldado12 = new GuerreroHumano("AguasdulcesSoldado2", 68, Arco3, Reino2, 45);
		GuerreroHumano Reino2Soldado13 = new GuerreroHumano("AguasdulcesSoldado3", 56, Hacha17, Reino2, 58);
		GuerreroHumano Reino2Soldado14 = new GuerreroHumano("AguasdulcesSoldado4", 48, Espada24, Reino2, 93);
		GuerreroHumano Reino2Soldado15 = new GuerreroHumano("AguasdulcesSoldado5", 46, Arco2, Reino2, 100);
		GuerreroHumano Reino2Soldado16 = new GuerreroHumano("AguasdulcesSoldado6", 85, Arco30, Reino2, 36);
		GuerreroHumano Reino2Soldado17 = new GuerreroHumano("AguasdulcesSoldado7", 85, Espada5, Reino2, 96);
		GuerreroHumano Reino2Soldado18 = new GuerreroHumano("AguasdulcesSoldado8", 40, Arco14, Reino2, 16);
		GuerreroHumano Reino2Soldado19 = new GuerreroHumano("AguasdulcesSoldado9", 38, Arco25, Reino2, 16);
		GuerreroHumano Reino2Soldado20 = new GuerreroHumano("AguasdulcesSoldado10", 57, Arco5, Reino2, 65);
		GuerreroHumano Reino3Soldado21 = new GuerreroHumano("El Nido de �guilasSoldado1", 77, Espada28, Reino3, 1);
		GuerreroHumano Reino3Soldado22 = new GuerreroHumano("El Nido de �guilasSoldado2", 62, Espada12, Reino3, 68);
		GuerreroHumano Reino3Soldado23 = new GuerreroHumano("El Nido de �guilasSoldado3", 43, Arco29, Reino3, 84);
		GuerreroHumano Reino3Soldado24 = new GuerreroHumano("El Nido de �guilasSoldado4", 74, Arco24, Reino3, 37);
		GuerreroHumano Reino3Soldado25 = new GuerreroHumano("El Nido de �guilasSoldado5", 43, Arco11, Reino3, 5);
		GuerreroHumano Reino3Soldado26 = new GuerreroHumano("El Nido de �guilasSoldado6", 31, Hacha20, Reino3, 68);
		GuerreroHumano Reino3Soldado27 = new GuerreroHumano("El Nido de �guilasSoldado7", 67, Arco9, Reino3, 36);
		GuerreroHumano Reino3Soldado28 = new GuerreroHumano("El Nido de �guilasSoldado8", 63, Espada30, Reino3, 16);
		GuerreroHumano Reino3Soldado29 = new GuerreroHumano("El Nido de �guilasSoldado9", 55, Arco20, Reino3, 14);
		GuerreroHumano Reino3Soldado30 = new GuerreroHumano("El Nido de �guilasSoldado10", 60, Hacha14, Reino3, 87);
		GuerreroHumano Reino4Soldado31 = new GuerreroHumano("Roca CasterlySoldado1", 77, Espada22, Reino4, 71);
		GuerreroHumano Reino4Soldado32 = new GuerreroHumano("Roca CasterlySoldado2", 64, Arco10, Reino4, 42);
		GuerreroHumano Reino4Soldado33 = new GuerreroHumano("Roca CasterlySoldado3", 46, Hacha15, Reino4, 98);
		GuerreroHumano Reino4Soldado34 = new GuerreroHumano("Roca CasterlySoldado4", 63, Arco6, Reino4, 12);
		GuerreroHumano Reino4Soldado35 = new GuerreroHumano("Roca CasterlySoldado5", 69, Espada18, Reino4, 44);
		GuerreroHumano Reino4Soldado36 = new GuerreroHumano("Roca CasterlySoldado6", 83, Arco12, Reino4, 73);
		GuerreroHumano Reino4Soldado37 = new GuerreroHumano("Roca CasterlySoldado7", 33, Espada7, Reino4, 34);
		GuerreroHumano Reino4Soldado38 = new GuerreroHumano("Roca CasterlySoldado8", 79, Hacha3, Reino4, 84);
		GuerreroHumano Reino4Soldado39 = new GuerreroHumano("Roca CasterlySoldado9", 70, Espada17, Reino4, 20);
		GuerreroHumano Reino4Soldado40 = new GuerreroHumano("Roca CasterlySoldado10", 38, Espada20, Reino4, 80);
		GuerreroHumano Reino5Soldado41 = new GuerreroHumano("Basti�n de las TormentasSoldado1", 62, Hacha28, Reino5, 14);
		GuerreroHumano Reino5Soldado42 = new GuerreroHumano("Basti�n de las TormentasSoldado2", 59, Hacha1, Reino5, 3);
		GuerreroHumano Reino5Soldado43 = new GuerreroHumano("Basti�n de las TormentasSoldado3", 69, Hacha7, Reino5, 81);
		GuerreroHumano Reino5Soldado44 = new GuerreroHumano("Basti�n de las TormentasSoldado4", 77, Hacha6, Reino5, 7);
		GuerreroHumano Reino5Soldado45 = new GuerreroHumano("Basti�n de las TormentasSoldado5", 80, Espada29, Reino5, 99);
		GuerreroHumano Reino5Soldado46 = new GuerreroHumano("Basti�n de las TormentasSoldado6", 75, Hacha25, Reino5, 92);
		GuerreroHumano Reino5Soldado47 = new GuerreroHumano("Basti�n de las TormentasSoldado7", 54, Hacha11, Reino5, 38);
		GuerreroHumano Reino5Soldado48 = new GuerreroHumano("Basti�n de las TormentasSoldado8", 83, Arco18, Reino5, 1);
		GuerreroHumano Reino5Soldado49 = new GuerreroHumano("Basti�n de las TormentasSoldado9", 73, Hacha18, Reino5, 97);
		GuerreroHumano Reino5Soldado50 = new GuerreroHumano("Basti�n de las TormentasSoldado10", 49, Hacha30, Reino5, 33);
		GuerreroHumano Reino6Soldado51 = new GuerreroHumano("Altojard�nSoldado1", 56, Arco26, Reino6, 57);
		GuerreroHumano Reino6Soldado52 = new GuerreroHumano("Altojard�nSoldado2", 46, Espada15, Reino6, 23);
		GuerreroHumano Reino6Soldado53 = new GuerreroHumano("Altojard�nSoldado3", 36, Hacha24, Reino6, 39);
		GuerreroHumano Reino6Soldado54 = new GuerreroHumano("Altojard�nSoldado4", 36, Hacha21, Reino6, 91);
		GuerreroHumano Reino6Soldado55 = new GuerreroHumano("Altojard�nSoldado5", 70, Espada14, Reino6, 74);
		GuerreroHumano Reino6Soldado56 = new GuerreroHumano("Altojard�nSoldado6", 66, Arco22, Reino6, 0);
		GuerreroHumano Reino6Soldado57 = new GuerreroHumano("Altojard�nSoldado7", 49, Hacha2, Reino6, 80);
		GuerreroHumano Reino6Soldado58 = new GuerreroHumano("Altojard�nSoldado8", 62, Espada27, Reino6, 26);
		GuerreroHumano Reino6Soldado59 = new GuerreroHumano("Altojard�nSoldado9", 60, Hacha27, Reino6, 35);
		GuerreroHumano Reino6Soldado60 = new GuerreroHumano("Altojard�nSoldado10", 78, Espada11, Reino6, 85);
		GuerreroHumano Reino7Soldado61 = new GuerreroHumano("Lanza del SolSoldado1", 48, Arco23, Reino1, 4);
		GuerreroHumano Reino7Soldado62 = new GuerreroHumano("Lanza del SolSoldado2", 31, Hacha4, Reino7, 61);
		GuerreroHumano Reino7Soldado63 = new GuerreroHumano("Lanza del SolSoldado3", 36, Espada9, Reino7, 18);
		GuerreroHumano Reino7Soldado64 = new GuerreroHumano("Lanza del SolSoldado4", 39, Arco13, Reino7, 1);
		GuerreroHumano Reino7Soldado65 = new GuerreroHumano("Lanza del SolSoldado5", 39, Arco21, Reino7, 94);
		GuerreroHumano Reino7Soldado66 = new GuerreroHumano("Lanza del SolSoldado6", 47, Arco1, Reino7, 4);
		GuerreroHumano Reino7Soldado67 = new GuerreroHumano("Lanza del SolSoldado7", 40, Espada4, Reino7, 28);
		GuerreroHumano Reino7Soldado68 = new GuerreroHumano("Lanza del SolSoldado8", 74, Espada3, Reino7, 76);
		GuerreroHumano Reino7Soldado69 = new GuerreroHumano("Lanza del SolSoldado9", 34, Arco28, Reino7, 18);
		GuerreroHumano Reino7Soldado70 = new GuerreroHumano("Lanza del SolSoldado10", 53, Arco16, Reino7, 63);
		CaminanteBlanco CaminanteSoldado71 = new CaminanteBlanco("Ejercito1Caminante1", 34, Espada26, true, 2);
		CaminanteBlanco CaminanteSoldado72 = new CaminanteBlanco("Ejercito1Caminante2", 68, Espada10, true, 1);
		CaminanteBlanco CaminanteSoldado73 = new CaminanteBlanco("Ejercito1Caminante3", 83, Espada1, false, 3);
		CaminanteBlanco CaminanteSoldado74 = new CaminanteBlanco("Ejercito1Caminante4", 82, Hacha13, true, 3);
		CaminanteBlanco CaminanteSoldado75 = new CaminanteBlanco("Ejercito1Caminante5", 78, Arco7, true, 3);
		CaminanteBlanco CaminanteSoldado76 = new CaminanteBlanco("Ejercito1Caminante6", 60, Hacha5, false, 1);
		CaminanteBlanco CaminanteSoldado77 = new CaminanteBlanco("Ejercito1Caminante7", 69, Hacha29, false, 3);
		CaminanteBlanco CaminanteSoldado78 = new CaminanteBlanco("Ejercito1Caminante8", 37, Hacha9, false, 1);
		CaminanteBlanco CaminanteSoldado79 = new CaminanteBlanco("Ejercito1Caminante9", 70, Espada6, false, 1);
		CaminanteBlanco CaminanteSoldado80 = new CaminanteBlanco("Ejercito1Caminante10", 59, Arco8, true, 1);
		CaminanteBlanco CaminanteSoldado81 = new CaminanteBlanco("Ejercito2Caminante11", 40, Hacha12, false, 3);
		CaminanteBlanco CaminanteSoldado82 = new CaminanteBlanco("Ejercito2Caminante12", 80, Arco27, true, 3);
		CaminanteBlanco CaminanteSoldado83 = new CaminanteBlanco("Ejercito2Caminante13", 45, Espada21, true, 1);
		CaminanteBlanco CaminanteSoldado84 = new CaminanteBlanco("Ejercito2Caminante14", 74, Arco15, true, 3);
		CaminanteBlanco CaminanteSoldado85 = new CaminanteBlanco("Ejercito2Caminante15", 45, Espada8, false, 3);
		CaminanteBlanco CaminanteSoldado86 = new CaminanteBlanco("Ejercito2Caminante16", 46, Hacha19, true, 2);
		CaminanteBlanco CaminanteSoldado87 = new CaminanteBlanco("Ejercito2Caminante17", 41, Hacha16, true, 1);
		CaminanteBlanco CaminanteSoldado88 = new CaminanteBlanco("Ejercito2Caminante18", 37, Hacha8, false, 2);
		CaminanteBlanco CaminanteSoldado89 = new CaminanteBlanco("Ejercito2Caminante19", 43, Espada13, false, 3);
		CaminanteBlanco CaminanteSoldado90 = new CaminanteBlanco("Ejercito2Caminante20", 63, Hacha23, false, 2);
		
		Arma.ColeccionArmas.add(Arco1);
		Arma.ColeccionArmas.add(Arco2);
		Arma.ColeccionArmas.add(Arco3);
		Arma.ColeccionArmas.add(Arco4);
		Arma.ColeccionArmas.add(Arco5);
		Arma.ColeccionArmas.add(Arco6);
		Arma.ColeccionArmas.add(Arco7);
		Arma.ColeccionArmas.add(Arco8);
		Arma.ColeccionArmas.add(Arco9);
		Arma.ColeccionArmas.add(Arco10);
		Arma.ColeccionArmas.add(Arco11);
		Arma.ColeccionArmas.add(Arco12);
		Arma.ColeccionArmas.add(Arco13);
		Arma.ColeccionArmas.add(Arco14);
		Arma.ColeccionArmas.add(Arco15);
		Arma.ColeccionArmas.add(Arco16);
		Arma.ColeccionArmas.add(Arco17);
		Arma.ColeccionArmas.add(Arco18);
		Arma.ColeccionArmas.add(Arco19);
		Arma.ColeccionArmas.add(Arco20);
		Arma.ColeccionArmas.add(Arco21);
		Arma.ColeccionArmas.add(Arco22);
		Arma.ColeccionArmas.add(Arco23);
		Arma.ColeccionArmas.add(Arco24);
		Arma.ColeccionArmas.add(Arco25);
		Arma.ColeccionArmas.add(Arco26);
		Arma.ColeccionArmas.add(Arco27);
		Arma.ColeccionArmas.add(Arco28);
		Arma.ColeccionArmas.add(Arco29);
		Arma.ColeccionArmas.add(Arco30);
		Arma.ColeccionArmas.add(Arco31);
		Arma.ColeccionArmas.add(Arco32);
		Arma.ColeccionArmas.add(Hacha1);
		Arma.ColeccionArmas.add(Hacha2);
		Arma.ColeccionArmas.add(Hacha3);
		Arma.ColeccionArmas.add(Hacha4);
		Arma.ColeccionArmas.add(Hacha5);
		Arma.ColeccionArmas.add(Hacha6);
		Arma.ColeccionArmas.add(Hacha7);
		Arma.ColeccionArmas.add(Hacha8);
		Arma.ColeccionArmas.add(Hacha9);
		Arma.ColeccionArmas.add(Hacha10);
		Arma.ColeccionArmas.add(Hacha11);
		Arma.ColeccionArmas.add(Hacha12);
		Arma.ColeccionArmas.add(Hacha13);
		Arma.ColeccionArmas.add(Hacha14);
		Arma.ColeccionArmas.add(Hacha15);
		Arma.ColeccionArmas.add(Hacha16);
		Arma.ColeccionArmas.add(Hacha17);
		Arma.ColeccionArmas.add(Hacha18);
		Arma.ColeccionArmas.add(Hacha19);
		Arma.ColeccionArmas.add(Hacha20);
		Arma.ColeccionArmas.add(Hacha21);
		Arma.ColeccionArmas.add(Hacha22);
		Arma.ColeccionArmas.add(Hacha23);
		Arma.ColeccionArmas.add(Hacha24);
		Arma.ColeccionArmas.add(Hacha25);
		Arma.ColeccionArmas.add(Hacha26);
		Arma.ColeccionArmas.add(Hacha27);
		Arma.ColeccionArmas.add(Hacha28);
		Arma.ColeccionArmas.add(Hacha29);
		Arma.ColeccionArmas.add(Hacha30);
		Arma.ColeccionArmas.add(Espada1);
		Arma.ColeccionArmas.add(Espada2);
		Arma.ColeccionArmas.add(Espada3);
		Arma.ColeccionArmas.add(Espada4);
		Arma.ColeccionArmas.add(Espada5);
		Arma.ColeccionArmas.add(Espada6);
		Arma.ColeccionArmas.add(Espada7);
		Arma.ColeccionArmas.add(Espada8);
		Arma.ColeccionArmas.add(Espada9);
		Arma.ColeccionArmas.add(Espada10);
		Arma.ColeccionArmas.add(Espada11);
		Arma.ColeccionArmas.add(Espada12);
		Arma.ColeccionArmas.add(Espada13);
		Arma.ColeccionArmas.add(Espada14);
		Arma.ColeccionArmas.add(Espada15);
		Arma.ColeccionArmas.add(Espada16);
		Arma.ColeccionArmas.add(Espada17);
		Arma.ColeccionArmas.add(Espada18);
		Arma.ColeccionArmas.add(Espada19);
		Arma.ColeccionArmas.add(Espada20);
		Arma.ColeccionArmas.add(Espada21);
		Arma.ColeccionArmas.add(Espada22);
		Arma.ColeccionArmas.add(Espada23);
		Arma.ColeccionArmas.add(Espada24);
		Arma.ColeccionArmas.add(Espada25);
		Arma.ColeccionArmas.add(Espada26);
		Arma.ColeccionArmas.add(Espada27);
		Arma.ColeccionArmas.add(Espada28);
		Arma.ColeccionArmas.add(Espada29);
		Arma.ColeccionArmas.add(Espada30);

		Reino.ColeccionReinos.add(Reino1);
		Reino.ColeccionReinos.add(Reino2);
		Reino.ColeccionReinos.add(Reino3);
		Reino.ColeccionReinos.add(Reino4);
		Reino.ColeccionReinos.add(Reino5);
		Reino.ColeccionReinos.add(Reino6);
		Reino.ColeccionReinos.add(Reino7);

		Personaje.ColeccionPersonajes.add(Reino1Soldado1);
		Personaje.ColeccionPersonajes.add(Reino1Soldado2);
		Personaje.ColeccionPersonajes.add(Reino1Soldado3);
		Personaje.ColeccionPersonajes.add(Reino1Soldado4);
		Personaje.ColeccionPersonajes.add(Reino1Soldado5);
		Personaje.ColeccionPersonajes.add(Reino1Soldado6);
		Personaje.ColeccionPersonajes.add(Reino1Soldado7);
		Personaje.ColeccionPersonajes.add(Reino1Soldado8);
		Personaje.ColeccionPersonajes.add(Reino1Soldado9);
		Personaje.ColeccionPersonajes.add(Reino1Soldado10);
		Personaje.ColeccionPersonajes.add(Reino1Soldado11);
		Personaje.ColeccionPersonajes.add(Reino1Soldado12);
		Personaje.ColeccionPersonajes.add(Reino2Soldado11);
		Personaje.ColeccionPersonajes.add(Reino2Soldado12);
		Personaje.ColeccionPersonajes.add(Reino2Soldado13);
		Personaje.ColeccionPersonajes.add(Reino2Soldado14);
		Personaje.ColeccionPersonajes.add(Reino2Soldado15);
		Personaje.ColeccionPersonajes.add(Reino2Soldado16);
		Personaje.ColeccionPersonajes.add(Reino2Soldado17);
		Personaje.ColeccionPersonajes.add(Reino2Soldado18);
		Personaje.ColeccionPersonajes.add(Reino2Soldado19);
		Personaje.ColeccionPersonajes.add(Reino2Soldado20);
		Personaje.ColeccionPersonajes.add(Reino3Soldado21);
		Personaje.ColeccionPersonajes.add(Reino3Soldado22);
		Personaje.ColeccionPersonajes.add(Reino3Soldado23);
		Personaje.ColeccionPersonajes.add(Reino3Soldado24);
		Personaje.ColeccionPersonajes.add(Reino3Soldado25);
		Personaje.ColeccionPersonajes.add(Reino3Soldado26);
		Personaje.ColeccionPersonajes.add(Reino3Soldado27);
		Personaje.ColeccionPersonajes.add(Reino3Soldado28);
		Personaje.ColeccionPersonajes.add(Reino3Soldado29);
		Personaje.ColeccionPersonajes.add(Reino3Soldado30);
		Personaje.ColeccionPersonajes.add(Reino4Soldado31);
		Personaje.ColeccionPersonajes.add(Reino4Soldado32);
		Personaje.ColeccionPersonajes.add(Reino4Soldado33);
		Personaje.ColeccionPersonajes.add(Reino4Soldado34);
		Personaje.ColeccionPersonajes.add(Reino4Soldado35);
		Personaje.ColeccionPersonajes.add(Reino4Soldado36);
		Personaje.ColeccionPersonajes.add(Reino4Soldado37);
		Personaje.ColeccionPersonajes.add(Reino4Soldado38);
		Personaje.ColeccionPersonajes.add(Reino4Soldado39);
		Personaje.ColeccionPersonajes.add(Reino4Soldado40);
		Personaje.ColeccionPersonajes.add(Reino5Soldado41);
		Personaje.ColeccionPersonajes.add(Reino5Soldado42);
		Personaje.ColeccionPersonajes.add(Reino5Soldado43);
		Personaje.ColeccionPersonajes.add(Reino5Soldado44);
		Personaje.ColeccionPersonajes.add(Reino5Soldado45);
		Personaje.ColeccionPersonajes.add(Reino5Soldado46);
		Personaje.ColeccionPersonajes.add(Reino5Soldado47);
		Personaje.ColeccionPersonajes.add(Reino5Soldado48);
		Personaje.ColeccionPersonajes.add(Reino5Soldado49);
		Personaje.ColeccionPersonajes.add(Reino5Soldado50);
		Personaje.ColeccionPersonajes.add(Reino6Soldado51);
		Personaje.ColeccionPersonajes.add(Reino6Soldado52);
		Personaje.ColeccionPersonajes.add(Reino6Soldado53);
		Personaje.ColeccionPersonajes.add(Reino6Soldado54);
		Personaje.ColeccionPersonajes.add(Reino6Soldado55);
		Personaje.ColeccionPersonajes.add(Reino6Soldado56);
		Personaje.ColeccionPersonajes.add(Reino6Soldado57);
		Personaje.ColeccionPersonajes.add(Reino6Soldado58);
		Personaje.ColeccionPersonajes.add(Reino6Soldado59);
		Personaje.ColeccionPersonajes.add(Reino6Soldado60);
		Personaje.ColeccionPersonajes.add(Reino7Soldado61);
		Personaje.ColeccionPersonajes.add(Reino7Soldado62);
		Personaje.ColeccionPersonajes.add(Reino7Soldado63);
		Personaje.ColeccionPersonajes.add(Reino7Soldado64);
		Personaje.ColeccionPersonajes.add(Reino7Soldado65);
		Personaje.ColeccionPersonajes.add(Reino7Soldado66);
		Personaje.ColeccionPersonajes.add(Reino7Soldado67);
		Personaje.ColeccionPersonajes.add(Reino7Soldado68);
		Personaje.ColeccionPersonajes.add(Reino7Soldado69);
		Personaje.ColeccionPersonajes.add(Reino7Soldado70);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado71);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado72);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado73);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado74);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado75);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado76);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado77);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado78);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado79);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado80);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado81);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado82);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado83);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado84);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado85);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado86);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado87);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado88);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado89);
		Personaje.ColeccionPersonajes.add(CaminanteSoldado90);

		Ejercito Ejercito1 = new Ejercito("Ejercito1", Reino1Soldado1);
		Ejercito Ejercito2 = new Ejercito("Ejercito2", Reino2Soldado11);
		Ejercito Ejercito3 = new Ejercito("Ejercito3", Reino3Soldado21);
		Ejercito Ejercito4 = new Ejercito("Ejercito4", Reino4Soldado31);
		Ejercito Ejercito5 = new Ejercito("Ejercito5", Reino5Soldado41);
		Ejercito Ejercito6 = new Ejercito("Ejercito6", Reino6Soldado51);
		Ejercito Ejercito7 = new Ejercito("Ejercito7", Reino7Soldado61);
		Ejercito Ejercito8 = new Ejercito("Ejercito8", CaminanteSoldado71);
		Ejercito Ejercito9 = new Ejercito("Ejercito9", CaminanteSoldado81);




		
		Ejercito.ColeccionEjercitos.add(Ejercito1);
		Ejercito.ColeccionEjercitos.add(Ejercito2);
		Ejercito.ColeccionEjercitos.add(Ejercito3);
		Ejercito.ColeccionEjercitos.add(Ejercito4);
		Ejercito.ColeccionEjercitos.add(Ejercito5);
		Ejercito.ColeccionEjercitos.add(Ejercito6);
		Ejercito.ColeccionEjercitos.add(Ejercito7);
		Ejercito.ColeccionEjercitos.add(Ejercito8);
		Ejercito.ColeccionEjercitos.add(Ejercito9);
		  

		
		Ejercito1.ColeccionSoldados.add(Reino1Soldado2);
		Ejercito1.ColeccionSoldados.add(Reino1Soldado3);
		Ejercito1.ColeccionSoldados.add(Reino1Soldado4);
		Ejercito1.ColeccionSoldados.add(Reino1Soldado5);
		Ejercito1.ColeccionSoldados.add(Reino1Soldado6);
		Ejercito1.ColeccionSoldados.add(Reino1Soldado7);
		Ejercito1.ColeccionSoldados.add(Reino1Soldado8);
		Ejercito1.ColeccionSoldados.add(Reino1Soldado9);
		Ejercito1.ColeccionSoldados.add(Reino1Soldado10);
		
		Ejercito2.ColeccionSoldados.add(Reino2Soldado12);
		Ejercito2.ColeccionSoldados.add(Reino2Soldado13);
		Ejercito2.ColeccionSoldados.add(Reino2Soldado14);
		Ejercito2.ColeccionSoldados.add(Reino2Soldado15);
		Ejercito2.ColeccionSoldados.add(Reino2Soldado16);
		Ejercito2.ColeccionSoldados.add(Reino2Soldado17);
		Ejercito2.ColeccionSoldados.add(Reino2Soldado18);
		Ejercito2.ColeccionSoldados.add(Reino2Soldado19);
		Ejercito2.ColeccionSoldados.add(Reino2Soldado20);
		
		Ejercito3.ColeccionSoldados.add(Reino3Soldado22);
		Ejercito3.ColeccionSoldados.add(Reino3Soldado23);
		Ejercito3.ColeccionSoldados.add(Reino3Soldado24);
		Ejercito3.ColeccionSoldados.add(Reino3Soldado25);
		Ejercito3.ColeccionSoldados.add(Reino3Soldado26);
		Ejercito3.ColeccionSoldados.add(Reino3Soldado27);
		Ejercito3.ColeccionSoldados.add(Reino3Soldado28);
		Ejercito3.ColeccionSoldados.add(Reino3Soldado29);
		Ejercito3.ColeccionSoldados.add(Reino3Soldado30);
		
		Ejercito4.ColeccionSoldados.add(Reino4Soldado32);
		Ejercito4.ColeccionSoldados.add(Reino4Soldado33);
		Ejercito4.ColeccionSoldados.add(Reino4Soldado34);
		Ejercito4.ColeccionSoldados.add(Reino4Soldado35);
		Ejercito4.ColeccionSoldados.add(Reino4Soldado36);
		Ejercito4.ColeccionSoldados.add(Reino4Soldado37);
		Ejercito4.ColeccionSoldados.add(Reino4Soldado38);
		Ejercito4.ColeccionSoldados.add(Reino4Soldado39);
		Ejercito4.ColeccionSoldados.add(Reino4Soldado40);
		
		Ejercito5.ColeccionSoldados.add(Reino5Soldado42);
		Ejercito5.ColeccionSoldados.add(Reino5Soldado43);
		Ejercito5.ColeccionSoldados.add(Reino5Soldado44);
		Ejercito5.ColeccionSoldados.add(Reino5Soldado45);
		Ejercito5.ColeccionSoldados.add(Reino5Soldado46);
		Ejercito5.ColeccionSoldados.add(Reino5Soldado47);
		Ejercito5.ColeccionSoldados.add(Reino5Soldado48);
		Ejercito5.ColeccionSoldados.add(Reino5Soldado49);
		Ejercito5.ColeccionSoldados.add(Reino5Soldado50);
		
		Ejercito6.ColeccionSoldados.add(Reino6Soldado52);
		Ejercito6.ColeccionSoldados.add(Reino6Soldado53);
		Ejercito6.ColeccionSoldados.add(Reino6Soldado54);
		Ejercito6.ColeccionSoldados.add(Reino6Soldado55);
		Ejercito6.ColeccionSoldados.add(Reino6Soldado56);
		Ejercito6.ColeccionSoldados.add(Reino6Soldado57);
		Ejercito6.ColeccionSoldados.add(Reino6Soldado58);
		Ejercito6.ColeccionSoldados.add(Reino6Soldado59);
		Ejercito6.ColeccionSoldados.add(Reino6Soldado60);
		
		Ejercito7.ColeccionSoldados.add(Reino7Soldado62);
		Ejercito7.ColeccionSoldados.add(Reino7Soldado63);
		Ejercito7.ColeccionSoldados.add(Reino7Soldado64);
		Ejercito7.ColeccionSoldados.add(Reino7Soldado65);
		Ejercito7.ColeccionSoldados.add(Reino7Soldado66);
		Ejercito7.ColeccionSoldados.add(Reino7Soldado67);
		Ejercito7.ColeccionSoldados.add(Reino7Soldado68);
		Ejercito7.ColeccionSoldados.add(Reino7Soldado69);
		Ejercito7.ColeccionSoldados.add(Reino7Soldado70);
		
		Ejercito8.ColeccionSoldados.add(CaminanteSoldado72);
		Ejercito8.ColeccionSoldados.add(CaminanteSoldado73);
		Ejercito8.ColeccionSoldados.add(CaminanteSoldado74);
		Ejercito8.ColeccionSoldados.add(CaminanteSoldado75);
		Ejercito8.ColeccionSoldados.add(CaminanteSoldado76);
		Ejercito8.ColeccionSoldados.add(CaminanteSoldado77);
		Ejercito8.ColeccionSoldados.add(CaminanteSoldado78);
		Ejercito8.ColeccionSoldados.add(CaminanteSoldado79);
		Ejercito8.ColeccionSoldados.add(CaminanteSoldado80);
		
		Ejercito9.ColeccionSoldados.add(CaminanteSoldado82);
		Ejercito9.ColeccionSoldados.add(CaminanteSoldado83);
		Ejercito9.ColeccionSoldados.add(CaminanteSoldado84);
		Ejercito9.ColeccionSoldados.add(CaminanteSoldado85);
		Ejercito9.ColeccionSoldados.add(CaminanteSoldado86);
		Ejercito9.ColeccionSoldados.add(CaminanteSoldado87);
		Ejercito9.ColeccionSoldados.add(CaminanteSoldado88);
		Ejercito9.ColeccionSoldados.add(CaminanteSoldado89);
		Ejercito9.ColeccionSoldados.add(CaminanteSoldado90);

		Reino1.ColeccionReinosFronterizos.add(Reino2);
		Reino2.ColeccionReinosFronterizos.add(Reino1);
		Reino2.ColeccionReinosFronterizos.add(Reino3);
		Reino2.ColeccionReinosFronterizos.add(Reino6);
		Reino3.ColeccionReinosFronterizos.add(Reino2);
		Reino4.ColeccionReinosFronterizos.add(Reino2);
		Reino5.ColeccionReinosFronterizos.add(Reino6);
		Reino5.ColeccionReinosFronterizos.add(Reino7);
		Reino6.ColeccionReinosFronterizos.add(Reino2);
		Reino6.ColeccionReinosFronterizos.add(Reino4);
		Reino6.ColeccionReinosFronterizos.add(Reino5);
		Reino6.ColeccionReinosFronterizos.add(Reino7);
		Reino7.ColeccionReinosFronterizos.add(Reino5);
		Reino7.ColeccionReinosFronterizos.add(Reino6);
		

		Batalla Batalla1 = new Batalla(Ejercito1,Ejercito2,Reino1,1980,03, 8);
		Batalla.ColeccionBatallas.add(Batalla1);
		
		Batalla Batalla2 = new Batalla(Ejercito1,Ejercito9,Reino1,1990,11, 7);
		Batalla.ColeccionBatallas.add(Batalla2);
		
		Batalla Batalla3 = new Batalla(Ejercito1,Ejercito9,Reino2,2001,04, 11);
		Batalla.ColeccionBatallas.add(Batalla3);
		
		Batalla Batalla4 = new Batalla(Ejercito2,Ejercito4,Reino4,2003,11, 12);
		Batalla.ColeccionBatallas.add(Batalla4);
		
		Batalla Batalla5 = new Batalla(Ejercito2,Ejercito3,Reino5,2016,07, 03);
		Batalla.ColeccionBatallas.add(Batalla5);
		
		Batalla Batalla6 = new Batalla(Ejercito9,Ejercito8,Reino7,2017,11, 03);
		Batalla.ColeccionBatallas.add(Batalla6);
	}
}
